### ISSUE TITLE
corrupted lazydata.yml if application crashes

### ISSUE THREAD

**Issue by rmanak** [rstojnic/lazydata#16]
I noticed when the python application that is tracking some data crashes at some point, it can leave behind a corrupted yaml file. It is not that uncommon when you are in an exploratory phase of building an ML model to write a code that can crash for example because of memory issues etc. It would be great if yaml file handle closes after each track call to ensure the file does not get corrupted! 
Thanks! I really like this project!

**Comment by rstojnic** [comment]
Will investigate. Any other details you can share? The file just looks incomplete?

**Comment by rmanak** [comment]
the file looks like binary file, `>> file lazydata.yml` says:
lazydata.yml: data
it doesn't look like ASCII text anymore. 
`>> cat lazydata.yml` looks like:
```
u�d֗��yz_����	>og��H���h4�B�{G���])I�\B�{G���)I�\B�{G���)I�\B�{G���)I�\B�{G���)I�\B�{G���)I�\X��^2���@�Ơ��3\��eЗ�"q�B�{G����)I�\l�KDv��^5bU{7�jB�{G���k
                                                    )I�\B�{G���)I�\~����Ɓw@�Cw�h�ۢ/<�Xq��4Oi�J��G����1��}6���{G����)I�\B�{G�:Z��ۮ(�2��a�B�{G����)I�\B�{G���)I�\B�{G���)I�\B�
```
my code looks something like this:

```
def get_data():
    df = pd.read_csv(track('data.csv'))
    return df
.
.
.
data = get_data()
.
.
model.fit(data_x, data_y,...)
```
Though please note that this code causes a full OS crash due to some issues with the GPU+Tensorflow
I tried to reproduce the same scenario by causing code crash using memory error or something, but the file looks fine in that case, I tired something like this:
```
import pandas as pd
import numpy as np
from lazydata import track

# pd.DataFrame.from_records([(1,2), (3,4)], columns=['A','B']).to_csv('out.csv')

def return_data():
    df = pd.read_csv(track('out.csv'))
    return df
    
_ = return_data()
a = np.random.random((1000000,100000000))
```

**Comment by rstojnic** [comment]
Thanks for testing this further! Good to hear it behaves as expected in a more controlled scikit-learn environment. My current hunch is that it's a low-level Tensorflow bug, but not quite sure how to proceed further to debug it. 

I looked at the code, and the only time when we write to the config file is in `Config.save_config()` which uses the `yaml` package to write out the yml file and then closes the file. 

So I think it's not an issue with a file that's not closed. To me this looks like a memory corruption problem, perhaps due to a low-level Tensorflow bug that overwrites some memory it shouldn't.

**Comment by rmanak** [comment]
Thanks for checking this out, yes most probably that is the case. Please feel free to close this issue. We have adopted this package for our data management for majority of our ML projects. Great project!
